package Vista;

import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

public class MenuPrincipal extends javax.swing.JFrame {

    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnActualizar = new javax.swing.JButton();
        quitarAviones = new javax.swing.JButton();
        prioridadAviones = new javax.swing.JButton();
        panelVuelos = new javax.swing.JPanel();
        generarVuelos = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemAyuda = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 350));
        setMinimumSize(new java.awt.Dimension(400, 350));

        btnActualizar.setText("Actualizar");
        btnActualizar.setActionCommand("agregar");

        quitarAviones.setText("Quitar");
        quitarAviones.setActionCommand("quitar");

        prioridadAviones.setText("Prioridad");
        prioridadAviones.setActionCommand("prioridad");

        generarVuelos.setText("Generar vuelos");
        generarVuelos.setActionCommand("generarVuelos");

        javax.swing.GroupLayout panelVuelosLayout = new javax.swing.GroupLayout(panelVuelos);
        panelVuelos.setLayout(panelVuelosLayout);
        panelVuelosLayout.setHorizontalGroup(
            panelVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVuelosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generarVuelos)
                .addGap(136, 136, 136))
        );
        panelVuelosLayout.setVerticalGroup(
            panelVuelosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelVuelosLayout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(generarVuelos)
                .addContainerGap())
        );

        jMenu1.setText("File");

        itemAyuda.setText("Ayuda");
        itemAyuda.setActionCommand("darAyuda");
        jMenu1.add(itemAyuda);

        itemSalir.setText("Salir");
        itemSalir.setActionCommand("salirE");
        jMenu1.add(itemSalir);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btnActualizar)
                .addGap(56, 56, 56)
                .addComponent(quitarAviones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(prioridadAviones)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVuelos, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelVuelos, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prioridadAviones)
                    .addComponent(quitarAviones)
                    .addComponent(btnActualizar))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JPanel getPanelVuelos() {
        return panelVuelos;
    }

    public JButton getAgregarAviones() {
        return btnActualizar;
    }

    public JButton getPrioridadAviones() {
        return prioridadAviones;
    }

    public JButton getQuitarAviones() {
        return quitarAviones;
    }

    public JButton getGenerarVuelos() {
        return generarVuelos;
    }

    public JMenuItem getItemAyuda() {
        return itemAyuda;
    }

    public JMenuItem getItemSalir() {
        return itemSalir;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton generarVuelos;
    private javax.swing.JMenuItem itemAyuda;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panelVuelos;
    private javax.swing.JButton prioridadAviones;
    private javax.swing.JButton quitarAviones;
    // End of variables declaration//GEN-END:variables
}
