/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author emman
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        setButtonGroup();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        checkBubleSort = new javax.swing.JCheckBox();
        checkInsertionSort = new javax.swing.JCheckBox();
        checkMergeSort = new javax.swing.JCheckBox();
        checkQuickSort = new javax.swing.JCheckBox();
        checkShellSort = new javax.swing.JCheckBox();
        checkMezclaDirecta = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbArchivosEncontrados = new javax.swing.JTable();
        txtBuscarArchivo = new javax.swing.JTextField();
        btnBuscarArchivo = new javax.swing.JToggleButton();
        txtBuscarDirectorio = new javax.swing.JTextField();
        btnBuscarDirectorio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbArchivosOrdenados = new javax.swing.JTable();
        checkDirectorios = new javax.swing.JCheckBox();

        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Proyecto Algoritmos de Ordenamiento");

        checkBubleSort.setText("Buble Sort");
        checkBubleSort.setActionCommand("bubleSort");

        checkInsertionSort.setText("Insertion Sort");
        checkInsertionSort.setActionCommand("insertionSort");

        checkMergeSort.setText("Merge Sort");
        checkMergeSort.setActionCommand("mergeSort");

        checkQuickSort.setText("Quick Sort");
        checkQuickSort.setActionCommand("quickSort");

        checkShellSort.setText("Shell Sort");
        checkShellSort.setActionCommand("shellSort");

        checkMezclaDirecta.setText("Mezcla Directa");
        checkMezclaDirecta.setActionCommand("mezclaDirecta");

        tbArchivosEncontrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Archivo", "Ruta", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbArchivosEncontrados);

        btnBuscarArchivo.setText("Buscar Archivo");
        btnBuscarArchivo.setActionCommand("buscarArchivo");

        btnBuscarDirectorio.setText("Buscar Directorio");
        btnBuscarDirectorio.setActionCommand("seleccionarRuta");

        jLabel2.setText("Lista de archivos encontrados");

        jLabel3.setText("Lista de archivos ordenados");

        tbArchivosOrdenados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Archivo", "Ruta", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbArchivosOrdenados);

        checkDirectorios.setText("todos los directorios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(checkBubleSort)
                                .addGap(30, 30, 30)
                                .addComponent(checkInsertionSort)
                                .addGap(35, 35, 35)
                                .addComponent(checkMergeSort)
                                .addGap(32, 32, 32)
                                .addComponent(checkQuickSort)
                                .addGap(18, 18, 18)))
                        .addGap(28, 28, 28)
                        .addComponent(checkShellSort)
                        .addGap(27, 27, 27)
                        .addComponent(checkMezclaDirecta)))
                .addContainerGap(66, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBuscarDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBuscarArchivo)
                            .addComponent(btnBuscarDirectorio)
                            .addComponent(checkDirectorios))
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(340, 340, 340))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarArchivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDirectorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkDirectorios)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBubleSort)
                    .addComponent(checkInsertionSort)
                    .addComponent(checkMergeSort)
                    .addComponent(checkQuickSort)
                    .addComponent(checkShellSort)
                    .addComponent(checkMezclaDirecta))
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    public JToggleButton getBtnBuscarArchivo() {
        return btnBuscarArchivo;
    }

    public JButton getBtnBuscarDirectorio() {
        return btnBuscarDirectorio;
    }

    public JCheckBox getCheckInsertionSort() {
        return checkInsertionSort;
    }

    public JCheckBox getCheckMergeSort() {
        return checkMergeSort;
    }

    public JCheckBox getCheckMezclaDirecta() {
        return checkMezclaDirecta;
    }

    public JCheckBox getCheckQuickSort() {
        return checkQuickSort;
    }

    public JCheckBox getCheckShellSort() {
        return checkShellSort;
    }

    public JCheckBox getChekBubleSort() {
        return checkBubleSort;
    }

    public JTable getTbArchivosEncontrados() {
        return tbArchivosEncontrados;
    }

    public JTable getTbArchivosOrdenados() {
        return tbArchivosOrdenados;
    }

    public JTextField getTxtBuscarArchivo() {
        return txtBuscarArchivo;
    }

    public JTextField getTxtBuscarDirectorio() {
        return txtBuscarDirectorio;
    }

    public void setButtonGroup() {
        buttonGroup1.add(checkBubleSort);
        buttonGroup1.add(checkShellSort);
        buttonGroup1.add(checkInsertionSort);
        buttonGroup1.add(checkMergeSort);
        buttonGroup1.add(checkMezclaDirecta);
        buttonGroup1.add(checkQuickSort);
    }

    public ButtonGroup getButtonGroup() {

        return buttonGroup1;
    }

    public JFileChooser getFileChooser() {
        return fileChooser;
    }

    public JCheckBox getCheckDirectorios() {
        return checkDirectorios;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBuscarArchivo;
    private javax.swing.JButton btnBuscarDirectorio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox checkBubleSort;
    private javax.swing.JCheckBox checkDirectorios;
    private javax.swing.JCheckBox checkInsertionSort;
    private javax.swing.JCheckBox checkMergeSort;
    private javax.swing.JCheckBox checkMezclaDirecta;
    private javax.swing.JCheckBox checkQuickSort;
    private javax.swing.JCheckBox checkShellSort;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbArchivosEncontrados;
    private javax.swing.JTable tbArchivosOrdenados;
    private javax.swing.JTextField txtBuscarArchivo;
    private javax.swing.JTextField txtBuscarDirectorio;
    // End of variables declaration//GEN-END:variables

}
