/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author emman
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {

            javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.mint.MintLookAndFeel");

        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();

        setButtonGroup();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbArchivosEncontrados = new javax.swing.JTable();
        txtBuscarArchivo = new javax.swing.JTextField();
        txtBuscarDirectorio = new javax.swing.JTextField();
        btnBuscarDirectorio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbArchivosOrdenados = new javax.swing.JTable();
        checkDirectorios = new javax.swing.JCheckBox();
        checkBubbleSort = new javax.swing.JRadioButton();
        checkMezclaDirecta = new javax.swing.JRadioButton();
        checkMergeSort = new javax.swing.JRadioButton();
        checkShellSort = new javax.swing.JRadioButton();
        checkQuickSort = new javax.swing.JRadioButton();
        checkInsertionSort = new javax.swing.JRadioButton();
        btnBuscarArchivo = new javax.swing.JButton();

        fileChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Proyecto Algoritmos de Ordenamiento");

        tbArchivosEncontrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Archivo", "Ruta", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbArchivosEncontrados);

        btnBuscarDirectorio.setText("Buscar Directorio");
        btnBuscarDirectorio.setActionCommand("seleccionarRuta");

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Lista de archivos encontrados");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Lista de archivos ordenados");

        tbArchivosOrdenados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre Archivo", "Ruta", "Fecha"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbArchivosOrdenados);

        checkDirectorios.setText("todos los directorios");

        checkBubbleSort.setText("Bubble Sort");
        checkBubbleSort.setActionCommand("bubbleSort");

        checkMezclaDirecta.setText("Mezcla Directa");
        checkMezclaDirecta.setActionCommand("mezclaDirecta");

        checkMergeSort.setText("Merge Sort");
        checkMergeSort.setActionCommand("mergeSort");

        checkShellSort.setText("Shell Sort");
        checkShellSort.setActionCommand("shellSort");

        checkQuickSort.setText("Quick Sort");
        checkQuickSort.setActionCommand("quickSort");

        checkInsertionSort.setText("Insertion Sort");
        checkInsertionSort.setActionCommand("insertionSort");

        btnBuscarArchivo.setText("Buscar Archivo");
        btnBuscarArchivo.setActionCommand("buscarArchivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtBuscarDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBuscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBuscarDirectorio)
                                    .addComponent(checkDirectorios)
                                    .addComponent(btnBuscarArchivo))
                                .addGap(116, 116, 116))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(287, 287, 287))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(234, 234, 234))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(48, 48, 48)
                            .addComponent(checkBubbleSort)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(178, 178, 178)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(38, 38, 38)
                                    .addComponent(checkMergeSort)
                                    .addGap(27, 27, 27)
                                    .addComponent(checkShellSort)
                                    .addGap(28, 28, 28)
                                    .addComponent(checkQuickSort)
                                    .addGap(18, 18, 18)
                                    .addComponent(checkInsertionSort)
                                    .addGap(37, 37, 37)
                                    .addComponent(checkMezclaDirecta))))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarArchivo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarDirectorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarDirectorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkDirectorios)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBubbleSort)
                    .addComponent(checkMezclaDirecta)
                    .addComponent(checkMergeSort)
                    .addComponent(checkShellSort)
                    .addComponent(checkQuickSort)
                    .addComponent(checkInsertionSort))
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnBuscarArchivo() {
        return btnBuscarArchivo;
    }

    public JButton getBtnBuscarDirectorio() {
        return btnBuscarDirectorio;
    }

    public JTable getTbArchivosEncontrados() {
        return tbArchivosEncontrados;
    }

    public JTable getTbArchivosOrdenados() {
        return tbArchivosOrdenados;
    }

    public JTextField getTxtBuscarArchivo() {
        return txtBuscarArchivo;
    }

    public JTextField getTxtBuscarDirectorio() {
        return txtBuscarDirectorio;
    }

    public void setButtonGroup() {
        buttonGroup1.add(checkBubbleSort);
        buttonGroup1.add(checkShellSort);
        buttonGroup1.add(checkInsertionSort);
        buttonGroup1.add(checkMergeSort);
        buttonGroup1.add(checkMezclaDirecta);
        buttonGroup1.add(checkQuickSort);
    }

    public ButtonGroup getButtonGroup() {

        return buttonGroup1;
    }

    public JFileChooser getFileChooser() {
        return fileChooser;
    }

    public JCheckBox getCheckDirectorios() {
        return checkDirectorios;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarArchivo;
    private javax.swing.JButton btnBuscarDirectorio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton checkBubbleSort;
    private javax.swing.JCheckBox checkDirectorios;
    private javax.swing.JRadioButton checkInsertionSort;
    private javax.swing.JRadioButton checkMergeSort;
    private javax.swing.JRadioButton checkMezclaDirecta;
    private javax.swing.JRadioButton checkQuickSort;
    private javax.swing.JRadioButton checkShellSort;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbArchivosEncontrados;
    private javax.swing.JTable tbArchivosOrdenados;
    private javax.swing.JTextField txtBuscarArchivo;
    private javax.swing.JTextField txtBuscarDirectorio;
    // End of variables declaration//GEN-END:variables

}
